<?php
// This file generated by Propel 1.6.0 convert-conf target
return array (
  'Adress' => 'propelleaks/Adress.php',
  'AdressPeer' => 'propelleaks/AdressPeer.php',
  'AdressQuery' => 'propelleaks/AdressQuery.php',
  'AdressTableMap' => 'propelleaks/map/AdressTableMap.php',
  'BaseAdress' => 'propelleaks/om/BaseAdress.php',
  'BaseAdressPeer' => 'propelleaks/om/BaseAdressPeer.php',
  'BaseAdressQuery' => 'propelleaks/om/BaseAdressQuery.php',
  'BasePerson' => 'propelleaks/om/BasePerson.php',
  'BasePersonPeer' => 'propelleaks/om/BasePersonPeer.php',
  'BasePersonQuery' => 'propelleaks/om/BasePersonQuery.php',
  'Person' => 'propelleaks/Person.php',
  'PersonPeer' => 'propelleaks/PersonPeer.php',
  'PersonQuery' => 'propelleaks/PersonQuery.php',
  'PersonTableMap' => 'propelleaks/map/PersonTableMap.php',
);