<?php
// This file generated by Propel 1.6.0 convert-conf target
// from XML runtime conf file /home/gpillet/workspace/PropelLeaks/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'propelleaks' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=propelleaks',
        'user' => 'root',
        'password' => '',
      ),
    ),
    'default' => 'propelleaks',
  ),
  'generator_version' => '1.6.0',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-propelleaks-conf.php');
return $conf;